# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    courses:
        label: Streak Type
        scope: applyStreakType
        modelClass: Voilaah\Gamify\Models\UserStreak
        options: getStreakTypesOptions
