list: $/voilaah/gamify/models/usermission/columns.yaml
modelClass: Voilaah\Gamify\Models\UserMissionProgress
title: User Missions
noRecordsMessage: "backend::lang.list.no_records"
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: "backend::lang.list.search_prompt"
recordUrl: voilaah/gamify/usermissions/update/:id
filter: config_filter.yaml
