# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/voilaah/gamify/models/badge/columns.yaml

# Model Class name
modelClass: Voilaah\Gamify\Models\Badge

# List Title
title: Manage Badges

# Link URL for each record
recordUrl: voilaah/gamify/badges/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Display page numbers with pagination, disable to improve performance
showPageNumbers: true

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting columns
# defaultSort:
#     column: [level, sort_order]
#     direction: [asc, asc]

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
