# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Badge

# Model Form Field configuration
form: $/voilaah/gamify/models/badge/fields.yaml

# Model Class name
modelClass: Voilaah\Gamify\Models\Badge

# Default redirect location
defaultRedirect: voilaah/gamify/badges

# Create page
create:
    title: backend::lang.form.create_title
    redirect: voilaah/gamify/badges/update/:id
    redirectClose: voilaah/gamify/badges

# Update page
update:
    title: backend::lang.form.update_title
    redirect: voilaah/gamify/badges
    redirectClose: voilaah/gamify/badges

# Preview page
preview:
    title: backend::lang.form.preview_title
