# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Reputation

# Model Form Field configuration
form: $/voilaah/gamify/models/reputation/fields.yaml

# Model Class name
modelClass: Voilaah\Gamify\Models\Reputation

# Default redirect location
defaultRedirect: voilaah/gamify/reputations

# Create page
create:
    title: backend::lang.form.create_title
    redirect: voilaah/gamify/reputations/update/:id
    redirectClose: voilaah/gamify/reputations

# Update page
update:
    title: backend::lang.form.update_title
    redirect: voilaah/gamify/reputations
    redirectClose: voilaah/gamify/reputations

# Preview page
preview:
    title: backend::lang.form.preview_title
